name: Docker Images CI - Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - uses: actions/checkout@v3
    - name: Build the Docker image Payments
      run: docker build . --file payments-service-example/Dockerfile --tag r41ss4/payment-service-t:$(date +%s)

    - uses: actions/checkout@v3
    - name: Build the Docker image Shipping
      run: docker build . --file shipping-service-example/Dockerfile --tag r41ss4/shipping-service-t:$(date +%s)

    - uses: actions/checkout@v3
    - name: Build the Docker image Products
      run: docker build . --file products-service-example/Dockerfile --tag r41ss4/products-service-t:$(date +%s)

    - uses: actions/checkout@v3
    - name: Build the Docker image Orders
      run: docker build . --file orders-service-example/Dockerfile --tag r41ss4/orders-service-t:$(date +%s)

    - name: Run the containers
      run: |
        docker run r41ss4/payment-service-t:$(date +%s)
        docker run r41ss4/shipping-service-t:$(date +%s)
        docker run r41ss4/products-service-t:$(date +%s)
        docker run r41ss4/orders-service-t:$(date +%s)