name: Docker Images CI - Main

# This workflow created docker images, upload them in the DockerHub and run the containers for the BE
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

# Login with Docker Hub, so that docker images are store and available there instead of locally
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

# Build Docker Images for each BE and upload them to Docker Hub
    - name: Build the Docker image Payments
      run: | 
        docker build . --file payments-service-example/Dockerfile --tag r41ss4/payments-service-t:$(date +%Y-%m-%d_H%)
        docker push r41ss4/payments-service-t:$(date +%Y-%m-%d_H%)
        docker run -d r41ss4/payments-service-t:latest

    - name: Build the Docker image Shipping
      run: |
        docker build . --file shipping-service-example/Dockerfile --tag r41ss4/shipping-service-t:$(date +%Y-%m-%d_H%)
        docker push r41ss4/shipping-service-t:$(date +%Y-%m-%d_H%)
        docker run -d r41ss4/shipping-service-t:latest

    - name: Build the Docker image Products
      run: |
        docker build . --file products-service-example/Dockerfile --tag r41ss4/products-service-t:$(date +%Y-%m-%d_H%)
        docker push r41ss4/products-service-t:$(date +%Y-%m-%d_H%)
        docker run -d r41ss4/products-service-t:latest

    - name: Build the Docker image Orders
      run: |
        docker build . --file orders-service-example/Dockerfile --tag r41ss4/orders-service-t:$(date +%Y-%m-%d_H%)
        docker push r41ss4/orders-service-t:$(date +%Y-%m-%d_H%)
        docker run -d r41ss4/orders-service-t:latest
